---

- name: influxdb-configure | Setup shared dir
  file: path=/opt/influxdb/shared state=directory owner=influxdb mode=0755

- name: influxdb-configure | Setup influxdb
  template: src=influxdb.conf.j2 dest=/etc/opt/influxdb/influxdb.conf
  notify: influxdb restart

- name: influxdb-configure | Ensure the service is started
  service: name=influxdb state=started

- name: influxdb-configure | Ensure http port is accepting connections
  wait_for: port={{ influxdb_http_bind_address.split(':')[1] }} delay=10

- name: influxdb-configure | Setup databases
  shell: curl -G "http://{{ influxdb_http_bind_address }}/query" --data-urlencode "q=CREATE DATABASE {{item}}"
  changed_when: false
  with_items: influxdb_databases

- name: influxdb-configure | Setup users pt. 1
  shell: curl -G "http://{{ influxdb_http_bind_address }}/query" --data-urlencode "q=CREATE USER {{item.username}} WITH PASSWORD '{{item.password}}'"
  changed_when: false
  with_items: influxdb_users

- name: influxdb-configure | Setup users pt. 2
  shell: curl -G "http://{{ influxdb_http_bind_address }}/query" --data-urlencode "q=GRANT ALL ON {{item.db}} TO '{{item.username}}'"
  changed_when: false
  with_items: influxdb_users
